/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuggestRouteImport } from './routes/suggest'
import { Route as ResultRouteImport } from './routes/result'
import { Route as PredictRouteImport } from './routes/predict'
import { Route as NichesRouteImport } from './routes/niches'
import { Route as ModelHealthRouteImport } from './routes/model-health'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DiagnoseRouteImport } from './routes/diagnose'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'

const SuggestRoute = SuggestRouteImport.update({
  id: '/suggest',
  path: '/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictRoute = PredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const NichesRoute = NichesRouteImport.update({
  id: '/niches',
  path: '/niches',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelHealthRoute = ModelHealthRouteImport.update({
  id: '/model-health',
  path: '/model-health',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnoseRoute = DiagnoseRouteImport.update({
  id: '/diagnose',
  path: '/diagnose',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/diagnose': typeof DiagnoseRoute
  '/history': typeof HistoryRoute
  '/model-health': typeof ModelHealthRoute
  '/niches': typeof NichesRoute
  '/predict': typeof PredictRoute
  '/result': typeof ResultRoute
  '/suggest': typeof SuggestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/diagnose': typeof DiagnoseRoute
  '/history': typeof HistoryRoute
  '/model-health': typeof ModelHealthRoute
  '/niches': typeof NichesRoute
  '/predict': typeof PredictRoute
  '/result': typeof ResultRoute
  '/suggest': typeof SuggestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/diagnose': typeof DiagnoseRoute
  '/history': typeof HistoryRoute
  '/model-health': typeof ModelHealthRoute
  '/niches': typeof NichesRoute
  '/predict': typeof PredictRoute
  '/result': typeof ResultRoute
  '/suggest': typeof SuggestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/diagnose'
    | '/history'
    | '/model-health'
    | '/niches'
    | '/predict'
    | '/result'
    | '/suggest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/diagnose'
    | '/history'
    | '/model-health'
    | '/niches'
    | '/predict'
    | '/result'
    | '/suggest'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/diagnose'
    | '/history'
    | '/model-health'
    | '/niches'
    | '/predict'
    | '/result'
    | '/suggest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  DiagnoseRoute: typeof DiagnoseRoute
  HistoryRoute: typeof HistoryRoute
  ModelHealthRoute: typeof ModelHealthRoute
  NichesRoute: typeof NichesRoute
  PredictRoute: typeof PredictRoute
  ResultRoute: typeof ResultRoute
  SuggestRoute: typeof SuggestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suggest': {
      id: '/suggest'
      path: '/suggest'
      fullPath: '/suggest'
      preLoaderRoute: typeof SuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predict': {
      id: '/predict'
      path: '/predict'
      fullPath: '/predict'
      preLoaderRoute: typeof PredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/niches': {
      id: '/niches'
      path: '/niches'
      fullPath: '/niches'
      preLoaderRoute: typeof NichesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-health': {
      id: '/model-health'
      path: '/model-health'
      fullPath: '/model-health'
      preLoaderRoute: typeof ModelHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnose': {
      id: '/diagnose'
      path: '/diagnose'
      fullPath: '/diagnose'
      preLoaderRoute: typeof DiagnoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  DiagnoseRoute: DiagnoseRoute,
  HistoryRoute: HistoryRoute,
  ModelHealthRoute: ModelHealthRoute,
  NichesRoute: NichesRoute,
  PredictRoute: PredictRoute,
  ResultRoute: ResultRoute,
  SuggestRoute: SuggestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
